### ISSUE TITLE
Game crashes when creating a game stage task or any trigger related with the task (in FTB Quests)

### ISSUE THREAD

**Issue by NitroNinja79** [FTBTeam/FTB-XMod-Compat#3]
[crash-2023-07-22_10.55.13-server.txt](https://github.com/FTBTeam/FTB-XMod-Compat/files/12141361/crash-2023-07-22_10.55.13-server.txt)

Above is the crash report, whenever I create a game stages task and enter a stage, whenever something triggers it (e.g. a command) the game will crash and you're not able to go back into that world.

This pretty much makes this mod unusable with FTB Quests and game stages. This is on version 1.19.2

**Comment by desht** [comment]
Fixed in 1.1.2 release: https://legacy.curseforge.com/minecraft/mc-mods/ftb-xmod-compat/files/4661647
